### ISSUE TITLE
Update and Create subscriptions does not work as expected

### ISSUE THREAD

**Issue by ashwin003** [Code2Gether-Discord/subtrack#100]
While creating subscriptions, `Billing occurrence` does not get saved with the value selected in the dropdown.
While updating subscriptions, `Billing interval` and `billing occurrence` does not get updated with the values from the UI.

**Comment by ashwin003** [comment]
100% on me. Foot in mouth moment 😅

**Comment by chrisK00** [comment]
> 100% on me. Foot in mouth moment 😅

How come it was closed? Want to solve it in #87?

**Comment by ashwin003** [comment]
Another mistake on my end. I thought I had created a branch; I hadn't. Sorry
