### ISSUE TITLE
Calculate total cost of subscriptions for a specific month

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#11]
### Suggested solution
- Add a method inside SubscriptionsCalculator that takes in subscriptions and the relevant month. It should return a List  containing the subscriptions. Only subscriptions that are going to be charged for that month should be returned. Paid subscriptions should not be included. Pass the result to the existing GetMonthlyCost method to get the cost for that specific month.
- add a SubscriptionsMonthResponse class to the Response folder containing the month and `ienumerable<subscriptionresponse>` which you can use to map the information youve gathered so far into a neat model
- Display the costs using a foreach loop with the already created display every month design from #10 

### Acceptance criteria
- A unit test has been added to validate the functionality works as expected now and in the future

**Comment by Pituzek** [comment]
https://github.com/Code2Gether-Discord/subtrack/pull/25
