### ISSUE TITLE
Monthly page call GetDueClass for due date

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#115]
### Notes
Inside SubscriptionMonthItem on this line 
`<div>@($"{sub.LastPayment.Day}{GetDateSuffix(sub.LastPayment.Day)}")</div> `
We should set the class of the div to whatever is returned from `CssUtil.GetDueClass`. We don't have access to the amount of days until its due so we need to calculate that, luckily we know the next payment date because it is stored inside `sub.LastPayment` and we can get the date of today `DateTime.Now.Date` so utilizing theese we should be able to calculate the amount of days until due/days it has been overdue.

**Comment by kgrontis** [comment]
@chrisK00 I don't think the `LastPayment` and  `DateTime.Now.Date` are enough to calculate the days until due. As i saw, we store Billing opoccurence and Billing interval as well on subscription. What formula did you have in mind?

I was thinking that this one should be ok for now:
```cs
public int GetDaysUntilDue(Subscription subscription)
{
    DateTime nextDueDate = new();
    switch (subscription.BillingOccurrence)
    {
        case BillingOccurrence.Month:
            nextDueDate = subscription.LastPayment.AddMonths(subscription.BillingInterval);
            break;
        case BillingOccurrence.Week:
            nextDueDate = subscription.LastPayment.AddWeeks(subscription.BillingInterval);
            break;
        case BillingOccurrence.Year:
            nextDueDate = subscription.LastPayment.AddYears(subscription.BillingInterval);
            break;
    }

    TimeSpan timeUntilDue = nextDueDate - DateTime.Now;

    return timeUntilDue.Days;
}
```

**Comment by chrisK00** [comment]
> @chrisK00 I don't think the `LastPayment` and  `DateTime.Now.Date` are enough to calculate the days until due. As i saw, we store Billing opoccurence and Billing interval as well on subscription. What formula did you have in mind?
> 
> I was thinking that this one should be ok for now:
> ```cs
> public int GetDaysUntilDue(Subscription subscription)
> {
>     DateTime nextDueDate = new();
>     switch (subscription.BillingOccurrence)
>     {
>         case BillingOccurrence.Month:
>             nextDueDate = subscription.LastPayment.AddMonths(subscription.BillingInterval);
>             break;
>         case BillingOccurrence.Week:
>             nextDueDate = subscription.LastPayment.AddWeeks(subscription.BillingInterval);
>             break;
>         case BillingOccurrence.Year:
>             nextDueDate = subscription.LastPayment.AddYears(subscription.BillingInterval);
>             break;
>     }
> 
>     TimeSpan timeUntilDue = nextDueDate - DateTime.Now;
> 
>     return timeUntilDue.Days;
> }
> ```

If we know the next payment date (its stored in the lastpayment date on the monthly page) then shouldnt it simply be sub.Lastpayment - today in order to get the difference between the dates and then calling something like .TotalDays

**Comment by kgrontis** [comment]
> its stored in the lastpayment date on the monthly page

This one I can't seem to be figuring out, can you please elaborate.

**Comment by chrisK00** [comment]
> > its stored in the lastpayment date on the monthly page
> 
> This one I can't seem to be figuring out, can you please elaborate.

Understandable its a bit missleading, we should probably  add a comment since we arent going to do smtn about it for now 😂 

SubscriptionMonthItem.razor has a foreach loop with subscriptions. Each subscription have a property called .LastPaymentDate but the twist is that it doesnt contain the LastPaymentDate in this context. Its actually the Next Payment Date. So if we know when the next payment date is, we can calculate how many days left from now till then
