### ISSUE TITLE
Details page Latest Payment text is duplicated

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#117]
The text "latest payment" is displayed in the label and next to the actual value. Remove the text before the actual value. Only the label should be kept.

![Screenshot_2023-09-07-22-41-28-055_com.companyname.subtrack.test.jpg](https://github.com/Code2Gether-Discord/subtrack/assets/72318023/6febb990-6b17-4109-b19c-0433e729121b)

Remove the text starting from the highlighted letter

**Comment by tejusmdn** [comment]
I will take this issue. Do you want the text aligned to the centre or to the left?

**Comment by chrisK00** [comment]
> I will take this issue. Do you want the text aligned to the centre or to the left?

Perfect! The date should be centered, similar to how the other values on the details page are

**Comment by tejusmdn** [comment]
@chrisK00 
After reading your Github workflow steps in the ReadMe file, I tried to create a branch for the issue and it looks like I do not have permission to create a branch. 

![image](https://github.com/Code2Gether-Discord/subtrack/assets/5728171/4537810b-bb9f-472c-aa56-e5901eb5b0b0)

**Comment by chrisK00** [comment]
> @chrisK00 
> After reading your Github workflow steps in the ReadMe file, I tried to create a branch for the issue and it looks like I do not have permission to create a branch. 
> 
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/5728171/4537810b-bb9f-472c-aa56-e5901eb5b0b0)
> 
> 
> 

I need to add you to the github team first, whats your username in the Code2gether discord?

**Comment by tejusmdn** [comment]
I am not part of the Code2gether discord channel yet. My discord username is te_jus.
