### ISSUE TITLE
Details page make labels less visible

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#128]
I'm not a big fan over the fact that the labels are in the same font and have the same alpha as the actual values. The dividers are also a bit distracting and we don't need as many as we currently have.

### Acceptance criteria
- The divider above the mark paid button has been removed
- The divider below delete button has been removed
- All dividers have a little less alpha values (decrease transparency)
- All labels are just a tiny bit smaller then previously and have a little less alpha values (decrease transparency)
- A screenshot of the result has been added to the pull request on github

**Comment by kgrontis** [comment]
How does this look?
![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/75481bc2-c412-438f-bd6b-5a3bff49358b)

**Comment by chrisK00** [comment]
> How does this look?
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/75481bc2-c412-438f-bd6b-5a3bff49358b)

Alpha is good. Font looks a bit too small, maybe increase it with like 1 pixel?
