### ISSUE TITLE
Design subscription list item

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#13]
Use the /docs/mockup.png as reference. Make use of bootstrap. The design should show the name, cost, if its auto paid and how many days left until its due. If it has been paid do not display it.

### Acceptance criteria
- Looks good on a ~1080x2400 (google pixel 5) resolution phone
- A png of the page is attached to the Pull request (not the repository code!) so that others don't need to run the code locally

**Comment by kgrontis** [comment]
@chrisK00 regarding below highlighted information

![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/f86340e7-f9f9-414c-ad80-6282bae96414)

From my understanding, this means that the last payment was on the 25th of June, and 6 days have passed. Is that correct, or am I interpreting this wrongly?

**Comment by chrisK00** [comment]
> @chrisK00 regarding below fighlighted information
> 
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/f86340e7-f9f9-414c-ad80-6282bae96414)
> 
> From my understanding, this means that the last payment was on the 25th of June, and 6 days have passed. Is that correct, or am I interpreting this wrongly?
> 
> 
> 

Image is out of date, later on decided to not list paid subs so dont have to care about the checkmark and all info is for the future

**Comment by kgrontis** [comment]
How does that look for a subscription list item?

![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/f569c374-f841-496c-8ead-7bbdc8c77cb2)

**Comment by chrisK00** [comment]
@kgrontis 
I would make it a card with a gray background like memsworth did. For auto paid maybe just type auto and for non auto paid you can leave it blank. For the auto text and date text make the font smaller so the first thing that catches your focus is the title and amount. Date only requires the day it's due f.e 26th

dc image: https://media.discordapp.net/attachments/1120394694447349941/1122608079700250685/image.png?width=488&height=905 
pr file: https://github.com/Code2Gether-Discord/subtrack/pull/22/files#diff-afb1e70a5fa707431520ee30d86de58b82d9aac43016fe7fb3fd308c4089fac1
