### ISSUE TITLE
add the ability to select a background/primary color 

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#130]
### Background
We will refer to the background color as the primary color. This is going to be used on the subscription card both on home and monthly page. This is a heavier task and will make changes all the way from the UI to the database so if you feel like its too large or you only want to do a part of it, make a sub-task or let me know and ill make one.

### TODO
- update cards background color on home and monthly page
- add a select list on upsert where you have  
    - only the following colors should be allowed (add a public readonly ienumerable of strings prop inside CssUtil): 
#theDefaultColor i think its #222
#281439
#34126d
#38354a
#22202c
#4b013b
#141c39
#34424c
#203d50
#13516d
#050505
#242424
#2e2e2e
#2d0903
    - It would be nice if the select list was actually grid styled so you don't have to scroll a long list of colors but it is not a requirement. default value should be should be the previously default value (think its #222 but you can go to bootswatch link in readme and inspect the fonts color using a chrome extension like eyedropper).
    - Each select item is basically a rectangle with a background of the color and with the entered subscription title, if its difficult for some reason to use the subscription title just hardcode an example text such as "lorem" or literally "example", "sample"
- On upsert move the description input field to the bottom of the page as showed in the mockups
- add the non nullable string field to the Subscription entity and when making the migration make sure to write hasdefault value inside the migration https://stackoverflow.com/questions/31025967/code-first-migration-how-to-set-default-value-for-new-property
- SubscriptionService when calling update or create the field should be mapped so that it is actually stored in the database

### Acceptance Criteria
- Existing users will have default colors of the previous colors
- When upserting a subscription we can select a primary color but it should not be required
- The subscription cards on home and monthly page has their background color set to the primary color

**Comment by ashwin003** [comment]
Chrome does have a color picker which gives the option of restricting available colors from a user defined palette. It shows up as a grid. 
But (AFAIK), it does not allow custom text within the picker, and it also has a "More" option, which gives the user the freedom to pick any color.

| Closed | Open | More |
| ----------- | ----------- | ----------- |
| ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/6dd90d55-1550-434c-82e8-1ace5bb53928) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/ce44c4b0-c09f-4c1e-9bf6-8015d2423603) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/276b25e8-f6b4-4fc5-841d-c01d760b0fc1) |

**Comment by chrisK00** [comment]
> Chrome does have a color picker which gives the option of restricting available colors from a user defined palette. It shows up as a grid. 
> But (AFAIK), it does not allow custom text within the picker, and it also has a "More" option, which gives the user the freedom to pick any color.
> 
> | Closed | Open | More |
> | ----------- | ----------- | ----------- |
> | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/6dd90d55-1550-434c-82e8-1ace5bb53928) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/ce44c4b0-c09f-4c1e-9bf6-8015d2423603) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/276b25e8-f6b4-4fc5-841d-c01d760b0fc1) |

This is perfect, nice find! We can skip the custom text/preview color for now. An idea for the future is that we maybe just separate the home page subscription card code from the home page to a component and then at the bottom of upsert display it
