### ISSUE TITLE
add the ability to select a icon and icon/secondary color

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#132]
### Background
We will refer to the icon color as the secondary color. This is going to be used as the icon color for the selected icon and the autopaid icon, it will also be color for dividers on the details page and used as border on the home page. This is a heavier task and will make changes all the way from the UI to the database so if you feel like its too large or you only want to do a part of it, make a sub-task or let me know and ill make one.

### Todo
- add a select list for icons on upsert where you have
    - only the following icons should be allowed (add a public readonly ienumerable of strings prop inside CssUtil):
_"fa-solid fa-music",
"fa-solid fa-house",
"fa-solid fa-lock",
"fa-brands fa-spotify",
"fa-solid fa-clapperboard",
"fa-solid fa-shield",
"fa-solid fa-shield-heart",
"fa-solid fa-key",
"fa-solid fa-credit-card",
"fa-solid fa-mobile",
"fa-solid fa-book",
"fa-solid fa-lines-leaning",
"fa-solid fa-gamepad",
"fa-solid fa-cloud-arrow-up",
"fa-solid fa-circle-play",
"fa-solid fa-tv",
"fa-solid fa-dumbbell",
"fa-solid fa-wifi",
"fa-solid fa-bolt",
"fa-solid fa-droplet",
"fa-solid fa-arrow-trend-up",
"fa-solid fa-money-bill",
"fa-solid fa-prescription-bottle-medical",
"fa-solid fa-spa",
"fa-solid fa-scissors",
"fa-solid fa-bicycle",_
    - the icon colors should be whatever is inside the secondary color value (can be achieved by doing style="color: @sub.SecondaryColor")
    - It would be nice if the select list was actually grid styled so you don't have to scroll a long list of icons but it is not a requirement. Maybe try this one or check for alternatives https://github.com/dogukanakkaya/iconpicker
- next to the icon select list there should be a color palette for selecting the secondary color
    - Default secondary color value should be the previously default value - the lightblue border on home page  (might be this one #2A9FD6 but you can go to bootswatch link in readme and inspect the fonts color using a chrome extension like eyedropper).
- Add the Icon nullable string field and SecondaryColor string field to the Subscription entity and when making the migration make sure to write hasdefault value inside the migration https://stackoverflow.com/questions/31025967/code-first-migration-how-to-set-default-value-for-new-property
- SubscriptionService when calling update or create the fields should be mapped so that it is actually stored in the database
- On the home and monthly page, display the icon on the left side of the titles
- On the home page, the icon should be displayed above the title, moving the title to move down one row
- make the cards rounded on the home page so they are like the cards on the monthly page. Inside the class="card-body" just add "rounded"

### Acceptance Criteria
- Existing users will have default colors of the previous colors and the default value for icon will be null
- When upserting a subscription we can select a secondary color (this is the equivalent of the icon color selector in the mockups so it should be next to the icon picker) and a icon but it should not be required to select either of thoose
- The dividers on details page has their color set to the secondary color
- The subscription cards border's color on home page should be set to the secondary color
- The subscription cards on home page and monthly should include the icon and its color should be the secondary color
- the autopaid icon on all pages should be set to the secondary color
- the icon is displayed on the details page

**Comment by ashwin003** [comment]
is there a defined palette for the secondary colors?

**Comment by chrisK00** [comment]
> is there a defined palette for the secondary colors?

Nope! Any color is allowed since it wont affect text readability, which is the reason we wanted to limit the bg to dark colors

**Comment by ashwin003** [comment]
https://github.com/dogukanakkaya/iconpicker works for the most part. 

Have to figure out how to detect whether a value has been selected. And the positioning could be better (library sets the position as an inline style). 

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/3039babe-101e-49a9-8fc0-5632e4584fec)
