### ISSUE TITLE
Details page change button's background to match the theme

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#134]
The mark paid button and the delete button seems to be using the default bootstrap coloring. Make sure the mark paid button has the class "btn-primary" and "btn-danger" for the delete button. The colors should be the same as the buttons in the theme https://bootswatch.com/cyborg/

**Comment by kgrontis** [comment]
Right now both buttons use the below classes that was asked on the bug to be used:
- Mark paid :"btn-primary"
- Delete : "btn-danger"

Do we want to make them look like the back button for example?
![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/0da1973e-f91d-4540-ac65-9206bb17ec09)

**Comment by chrisK00** [comment]
> Right now both buttons use the below classes that was asked on the bug to be used:
> - Mark paid :"btn-primary"
> - Delete : "btn-danger"
> 
> Do we want to make them look like the back button for example?
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/0da1973e-f91d-4540-ac65-9206bb17ec09)
> 
> 
> 

Weird, I wonder whats overriding the default styling. We can just manually set the background-colors then to the same colors as the ones in the theme. The buttons should not be outlined however like the back btn is right now

**Comment by chrisK00** [comment]
> Right now both buttons use the below classes that was asked on the bug to be used:
> - Mark paid :"btn-primary"
> - Delete : "btn-danger"
> 
> Do we want to make them look like the back button for example?
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/7747808/0da1973e-f91d-4540-ac65-9206bb17ec09)
> 
> 
> 

Just checked it seems like its caused by the defualt styling inside app.css. so in this issue we can remove any styling that targets the buttons, goal would ofc be to cleanup everything thats unused but theres probs something we are currently making use of e.g mb links
