### ISSUE TITLE
Implement GetMonthlyCost method

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#3]
### Background
We need to display the monthly cost of subscriptions on the startpage in a way that allows us to test the calculation logic.

### Suggested solution
- Add a static SubscriptionsCalculator class with a GetMonthlyCost extension method inside the services folder that takes in an IEnumerable<Subscription>
- The method should return the total cost of the subscriptions for this month

### Acceptance criteria
- A unit test has been added to validate the functionality works as expected now and in the future

**Comment by kgrontis** [comment]
Completed the implementation of the method with PR #18
