### ISSUE TITLE
Add a go back button component

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#35]
Design ref in /docs/MVP mockups.png

### Suggested solution
- icon https://icons.getbootstrap.com/icons/arrow-left-square/
- add the design for a go back button that will be used in the top left corner on upsert and details page.
- On click this should return to whatever page that the user was previously on. That means when adding the component to a page they need to specify a required parameter, the return url              
- make use of NavigationManager

**Comment by bigggmoustache** [comment]
Actually Chris can we not use the icons with borders since our CSS has border buttons?
![image](https://github.com/Code2Gether-Discord/subtrack/assets/92475149/04b186bd-e560-4d1a-9ed4-b2e3ef9ec885)
`<NavLink class="btn btn-light;" data-bs-theme="dark" href="@ReturnUrl">
        <i class="bi bi-arrow-left-square" style="font-size: 30px;"></i>
    </NavLink>`

**Comment by chrisK00** [comment]
> Actually Chris can we not use the icons with borders since our CSS has border buttons?
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/92475149/04b186bd-e560-4d1a-9ed4-b2e3ef9ec885)
> `<NavLink class="btn btn-light;" data-bs-theme="dark" href="@ReturnUrl">
>         <i class="bi bi-arrow-left-square" style="font-size: 30px;"></i>
>     </NavLink>`

Any icon is suitable. Is there a reason why we need the class=btn though? Another option is simply to override that styling

**Comment by bigggmoustache** [comment]
I did this in the upsert PR jsyk. Sorry!

**Comment by chrisK00** [comment]
> I did this in the upsert PR jsyk. Sorry!

No worries, just type "closes "#35" in the PR description so the issue gets linked
