### ISSUE TITLE
Update design on Upsert page

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#41]
Do not create a new page but rather update #30

### Suggested solution
- add a optional query parameter named id so you can fetch the existing subscription if it is provided
- edit button is showed if id was provided https://icons.getbootstrap.com/icons/check-square/
- on submit subscriptionservice.update should be called instead of create if id is provided

**Comment by bigggmoustache** [comment]
Howdy bud. I'm confused how this in practice relates to the previous issue.
Is it a new page that you can query and loads the upsert page if found?

**Comment by chrisK00** [comment]
> Howdy bud. I'm confused how this in practice relates to the previous issue.
> Is it a new page that you can query and loads the upsert page if found?

This issue is made so that if someone clicks on a sub and then clicks on the edit button they are taken to the upsert page. Its the same page as the create but we need to add some specific logic in order to edit an existing sub if an id was sent. We should be able to use multiple routes here so one is the current /create and the other is /edit/id
