### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#55]
We are currently running .NET 6 in all projects. Github action uses the .net 7 SDK due to the .NET 8 not being able to build .net 6 MAUI

### ✅ Investigate
✅ Before changing the version of the MAUI project, make sure to deploy the app to an android phone in release mode and comment below:
- app size (my was 49.33mb)
- approximate startup time in seconds (my was 3s)

✅ After changing the version, deploy the app again and add a new comment down below with the results and if any new errors occurs

### Acceptance Criteria
- Change the github action to target .NET 7 and remove the temp code
- Upgrade all projects to .NET 7
- Upgrade all nuget packages to the latest versions
- update global.json

**Comment by ashwin003** [comment]
.NET 7

aab file: 42.0MB
apk file: 44.9MB
approx startup time: 2.2s

device used: Nothing Phone 1
android version: 13

**Comment by chrisK00** [comment]
> .NET 7
> 
> aab file: 42.0MB
> apk file: 44.9MB
> approx startup time: 2.2s
> 
> device used: Nothing Phone 1
> android version: 13

Can you also test with NET 6?

**Comment by ashwin003** [comment]
build fails on .NET 6 for me. Not sure why. 

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/fda934b7-a915-4da7-b54f-eb92e062102e)

**Comment by chrisK00** [comment]
> build fails on .NET 6 for me. Not sure why. 
> 
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/fda934b7-a915-4da7-b54f-eb92e062102e)
> 

Did you try removing the project locally and cloning again? Do you have .NET 6 installed and the other required items for MAUI dev? 

This might be helpful (scroll to the bottom) https://github.com/dotnet/maui/issues/5778

**Comment by ashwin003** [comment]
Did you try removing the project locally and cloning again: Yes
 Do you have .NET 6 installed and the other required items for MAUI dev: I installed .NET 6 yesterday, and the other components as well
 
 
![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/ebc58102-6e03-4de0-9488-001a2ab6529c)

**Comment by chrisK00** [comment]
> Did you try removing the project locally and cloning again: Yes
>  Do you have .NET 6 installed and the other required items for MAUI dev: I installed .NET 6 yesterday, and the other components as well
>  
>  
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/ebc58102-6e03-4de0-9488-001a2ab6529c)
> 

Lmk if any of the solutions in the link like adding a global.json solves it. Someone mentioned its an issue w .net 7, maybe try uninstalling that and any preview versions you have?

**Comment by chrisK00** [comment]
.NET 7

- app size: 51mb - increase by 2mb
- startup time: same ~3s

I did not upgrade all packages tho, only the projects

I would prefer waiting and upgrading to .NET 8 when it's released, but if you @ashwin003  are still unable to solve the errors with .NET 6 you can make the upgrade.

**Comment by ashwin003** [comment]
Didn't work 😔. I changed the projects to .NET 7 while working on the details page and reverted to 6 before pushing the changes.

**Comment by chrisK00** [comment]
> Didn't work 😔. I changed the projects to .NET 7 while working on the details page and reverted to 6 before pushing the changes.

What solutions did you try?

**Comment by ashwin003** [comment]
> > Didn't work 😔. I changed the projects to .NET 7 while working on the details page and reverted to 6 before pushing the changes.
> 
> What solutions did you try?

remove and reinstall VS, .NET, maui workloads

**Comment by chrisK00** [comment]
> > > Didn't work 😔. I changed the projects to .NET 7 while working on the details page and reverted to 6 before pushing the changes.
> > 
> > What solutions did you try?
> 
> remove and reinstall VS, .NET, maui workloads

Did you try the global.json?

**Comment by ashwin003** [comment]
> > > > Didn't work 😔. I changed the projects to .NET 7 while working on the details page and reverted to 6 before pushing the changes.
> > > 
> > > 
> > > What solutions did you try?
> > 
> > 
> > remove and reinstall VS, .NET, maui workloads
> 
> Did you try the global.json?

yes

**Comment by chrisK00** [comment]
@ashwin003 Did it work out for you in the end?

**Comment by ashwin003** [comment]
> @ashwin003 Did it work out for you in the end?

Nope. I have given up and now these three are permanently checked out in my system

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/2ab07640-fb94-4366-9dd8-5d524a188978)

**Comment by chrisK00** [comment]
> > @ashwin003 Did it work out for you in the end?
> 
> Nope. I have given up and now these three are permanently checked out in my system
> 
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/2ab07640-fb94-4366-9dd8-5d524a188978)
> 

Rofl ok just wanted to know if we should keep the issue open or close it
