### ISSUE TITLE
Mark auto paid subs as paid

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#70]
### Background
There is an option to make a subscription's next payment paid automatically when due but the logic for doing so has not been implemented

### Issues
- [x] #69
- [x] #71
- [x] #72
- [x] #73
- [x] #74

**Comment by bigggmoustache** [comment]
I forgot I took this, sorry! I'll do them tomorrow!
edit: sorry for not getting around to it!
