### ISSUE TITLE
Subscriptions page Display every month and the total cost

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#8]
### User story
As a user
I want to see each month's expense amount
So that I can plan my budget for the future

### Subtasks
- [x] #9 
- [x] #10
- [x] #11

**Comment by nabeelfarooqui98** [comment]
Won't every month be the same amount? Unless we keep track of when subscriptions start and end which I don't think we're doing at the moment

**Comment by chrisK00** [comment]
> Won't every month be the same amount? Unless we keep track of when subscriptions start and end which I don't think we're doing at the moment 

You are technically right, the reason is that currently we only support monthly subscriptions (no way of adding when the sub reoccurs) but that will probably be the first feature to add after MVP.2
