### ISSUE TITLE
Update GetYearlyCost to make use of billing cycle

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#85]
The formula inside GetYearlyCost() only works for subscriptions paid every 1 month. With the introduction of occurrence and interval, the formula needs to be updated. The formula is currently cost * amountOfMonthsInAYear and the amountOfMonthsInAYear is what needs to be changed depending on the occurrence (month, week) and interval of the sub.

### Suggestions
- You do not need to calculate yearly subscriptions as these wont be displayed 
- Getting the amount of weeks in a year https://learn.microsoft.com/en-us/dotnet/api/system.globalization.isoweek.getweeksinyear?view=net-7.0
- if in the formula cost * timesPaid exceds 1 year (f.e if a subscription is monthly but has an interval that is > 12 or if its weekly with an interval > amountOfWeeks in a Year) we should throw a notimplementedexception with a message saying "Only billing Cycles within a year are supported". Do the same if its a yearly subscription. We could make a helper method inside SubCalc named BillingCycleExcedsOneYear() since this is also used in #84 

### Acceptance Criteria
- Do not change input test data of existing tests for this method if they exist. Theese should pass if the method has been implemented correctly
- Tests have been added to cover the new subscription type and the addition of intervals

**Comment by ashwin003** [comment]
This what you have in mind?

```csharp
public decimal GetYearlyCost(Subscription subscription)
{
    if (subscription is null)
        throw new ArgumentNullException(nameof(subscription));
    var weeksInYear = ISOWeek.GetWeeksInYear(DateTime.Now.Year);
    var billingInterval = (subscription.BillingOccurrence, subscription.BillingInterval) switch
    {
        (BillingOccurrence.Year, 1) => 1,
        (BillingOccurrence.Month, var monthlyInterval) when monthlyInterval <= _monthsInAYear => _monthsInAYear / monthlyInterval,
        (BillingOccurrence.Week, var weeklyInterval) when weeklyInterval <= weeksInYear => weeksInYear / weeklyInterval,
        _ => throw new NotImplementedException("Only billing Cycles within a year are supported")
    };
    return subscription.Cost * billingInterval;
}
```

**Comment by chrisK00** [comment]
> This what you have in mind?
> 
> ```csharp
> public decimal GetYearlyCost(Subscription subscription)
> {
>     if (subscription is null)
>         throw new ArgumentNullException(nameof(subscription));
>     var weeksInYear = ISOWeek.GetWeeksInYear(DateTime.Now.Year);
>     var billingInterval = (subscription.BillingOccurrence, subscription.BillingInterval) switch
>     {
>         (BillingOccurrence.Year, 1) => 1,
>         (BillingOccurrence.Month, var monthlyInterval) when monthlyInterval <= _monthsInAYear => _monthsInAYear / monthlyInterval,
>         (BillingOccurrence.Week, var weeklyInterval) when weeklyInterval <= weeksInYear => weeksInYear / weeklyInterval,
>         _ => throw new NotImplementedException("Only billing Cycles within a year are supported")
>     };
>     return subscription.Cost * billingInterval;
> }
> ```

- skip the Yearly case because if its yearly they shouldnt even call this method as of now
- var billingInterval could be named yearlyPaymentsCount
- use datetimeservice for getting current year

Otherwise yes that is pretty much it. Well done
