### ISSUE TITLE
Update GetSubscriptionListByMonth to make use of Billing Cycle

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#87]
We need to display every upcoming subscription payment, GetSubscriptionListByMonth has to consider occurrence and interval when returning what subscription payments are due the requested date.

#### interval 1 
- lastPayment is 1th
- How many weeks are left this month where we should pay the sub?: 3
- That means we need to return this subscription 3 times, and each time with a different next payment
- The next payment is Aug 8, after that Aug 15, and the final one is Aug 22

####  interval 2 
- lastPayment is 1th
- How many weeks are left this month where we should pay the sub?: 2
- That means we need to return this subscription 2 times, and each time with a different next payment
- The next payment is Aug 15, final payment is Aug 29

#### interval 3 
- lastPayment is 1th
- How many weeks are left this month where we should pay the sub?: 1
- That means we need to return this subscription 1 time
- The next and final payment is Aug 22

### Ideas
- Since we need to subsequently get the next payment date we could make use of GetNextPaymentDate()

### Acceptance Criteria
- Tests have been added to cover the new subscription types
- Do not change input test data of existing Tests for GetSubscriptionListByMonth that test monthly occurrence. Theese should pass if the method has been implemented correctly

**Comment by ashwin003** [comment]
paramount: once every two weeks
disney plus, netflix: once a month
hbo: once a year
hulu: once every 3 months

| Pic 1| Pic 2 | Pic 3 |
| ----------- | ----------- | ----------- |
|  ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/0f0d1d74-019d-49b7-bdf2-959d2bf4df6c) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/5f3cd318-19b4-4f05-adc7-2a05cb02f933) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/7a88213d-f422-4d0e-8d7c-8e84f1dcb027) |


update: sorting by date

**Comment by chrisK00** [comment]
> paramount: once every two weeks
> disney plus, netflix: once a month
> hbo: once a year
> hulu: once every 3 months
> 
> | Pic 1| Pic 2 | Pic 3 |
> | ----------- | ----------- | ----------- |
> |  ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/0f0d1d74-019d-49b7-bdf2-959d2bf4df6c) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/5f3cd318-19b4-4f05-adc7-2a05cb02f933) | ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/7a88213d-f422-4d0e-8d7c-8e84f1dcb027) |
> 
> 
> update: sorting by date
> 
> 
> 
> 
> 
> 
> 
> 

Looking good!
