### ISSUE TITLE
Implement GetAverageMonthlyCost for Home page Monthly cost

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#89]
The current way of displaying the monthly total cost is getting the sum of all subscriptions. With some subscriptions being weekly, some having an interval of 15 etc... we need to change the way we calculate this. Add a new method that also takes in a list of subscriptions. The monthly cost that is returned should be the average monthly cost of subscriptions

#### 1
Input data: `[ {Occurrence:Year, Interval: 1, Cost: 24 } ]`
Average monthly cost is Cost / monthsInAYear = 2

#### 2
Input data: `[ {Occurrence: Week, Interval: 1, Cost: 5} ]`
Average monthly cost is Cost / (weeksInTheCurrentYear/monthsInAYear) = ~21.5 

#### 3
Input data: `[ {Occurrence: Week, Interval: 2, Cost: 5} ]`
Average monthly cost is Cost / ((weeksInTheCurrentYear / interval ) / monthsInAYear) = ~10.8

### Acceptance criteria
- Tests have been added
- On the start page you can see that the monthly cost is approximate - using an tilde "~" next to the value

**Comment by ashwin003** [comment]
![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/94431057-9a25-4979-84c9-e431c5ca4209)

**Comment by chrisK00** [comment]
> ![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/94431057-9a25-4979-84c9-e431c5ca4209)
> 

Lgtm
