### ISSUE TITLE
Make nav buttons larger and remove outline on back, save and edit buttons

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#91]
### Acceptance Criteria
- Home and monthly button should be slightly larger both width and height. Theres a line above them that is too close, it should also be slightly moved upwards 
- Back and Edit button on sub details should not be outlined
- Back and Save button on sub upsert should not be outlined
- A png of the page is attached to the Pull request (not the repository code)
- Looks good on a ~1080x2400 (google pixel 5)

**Comment by chrisK00** [comment]
Hey @Penguine-Os, any updates on this?

**Comment by Penguine-Os** [comment]
Hi, 
ive almost completed the task.
i would like to improve the navbar component... 
I suggest to remove the "Home" & "Monthely" text al together and only keep the icons and mayebe replace the monthely icon with a calender icon think this is more inline with many ui/ux guidlines.

What do you think?

**Comment by chrisK00** [comment]
> Hi, 
> ive almost completed the task.
> i would like to improve the navbar component... 
> I suggest to remove the "Home" & "Monthely" text al together and only keep the icons and mayebe replace the monthely icon with a calender i think this is more inline with many ui/ux guidlines.
> 
> What do you think?

Hey, I think a calendar icon instead of the current one on monthly sounds great. Regarding removing the text below the icons afaik its very common to have an icon and then text that explains where it links to but Im a fan of simplicity so give it a try! If you remove the text make sure to make the icons larger so they are easy to click
