### ISSUE TITLE
Allow longer titles than 12 characters

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#92]
When developing the MVP we created #58 as a quick fix. Longer titles should be allowed but need to be displayed differently in order to not reproduce #58.

### Suggested solution
- Check the details page, is there any limit on how long a title can be there? If there is no limit in the details page change the data annotation on sub title to be **50**. If there is a limit however try to make it possible to exceed it, otherwise change the data annotation to be whatever that limit is
- Increase the width of each sub card and try to find out the maximum amount of characters until the page breaks. Both on the Home and Monthly page.
- Any characters that exceed the max amount of characters on a sub on the Home or Monthly page should not be included and you should suffix the title with 3 dots "...". For example if the max possible character count on the home/monthly page is **15** and the title of a sub is **"Testing123AgainAnd456"** then you should display **"Testing123Ag..."**

### Acceptance criteria
- Reproducing #58 should not be possible
- Titles with more than 12 characters should be allowed, at least 20 characters should be possible
- A png of the page is attached to the Pull request (not the repository code)
- Looks good on a ~1080x2400 (google pixel 5)

**Comment by ashwin003** [comment]
Max width: 20 characters
Sub card max width: unchanged

![image](https://github.com/Code2Gether-Discord/subtrack/assets/12110372/13acec16-1a09-4fd3-aba9-aff2a6a2fb2c)
