### ISSUE TITLE
Extend GetYearlyCost method to get average yearly cost

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/subtrack#99]
### Background
It was difficult to decide on what made sense to display for #85 but Ive seen that we need to have a look at previous payments to properly calculate the actual cost for this year in order to get the correct amount of payments left this year due to interval. Since we are not storing payments and there are no plans for doing so we should approach this differently in order for the annual cost to still make sense

**Example**
Interval of 7 for a monthly sub
Year 1 we pay the subscription in July only once
Year 2 we pay the subscription in february and also in October meaning we have 2 payments that year

# Requirements
- calculate average cost of a subscription for one year. Including Yearly subscriptions even if they have an interval > 1. The implementation is probably the same as the one inside #89 so we can most likely just take the result from it and multiply by 12, alternatively we implement the code for average cost per year here and they can divide by 12 
- as usual there should be tests that verify the calculations are correct
- Rename the method to GetAverageYearlyCost

**Comment by bigggmoustache** [comment]
What is meant by "Extend GetYearlyCost method"? At the end you say to rename to "GetAverageYearlyCost" which makes me unsure.

**Comment by bigggmoustache** [comment]
Doesn't the GetYearlyCost already get the average cost through the following?
yearlyPaymentCount = monthsInAYear / monthlyInterval;
return subsription.Cost * yearlyPaymentCount;

edit: I just stepped through and saw it's an int, so it doesn't get actual average. I can just use decimal and it will return an actual average?

"calculate average cost of a subscription for one year. Including Yearly subscriptions even if they have an interval > 1"

Sorry I'm having trouble understanding this bit.

**Comment by bigggmoustache** [comment]
Since I didn't understand the assignment, this is what I've done so far 
![image](https://github.com/Code2Gether-Discord/subtrack/assets/92475149/f3eb0af6-748e-46b4-a941-b0e8d30b5dba)

You also want greater than one year subscription functionality added, and tests yeah?

**Comment by chrisK00** [comment]
> Doesn't the GetYearlyCost already get the average cost through the following?
> yearlyPaymentCount = monthsInAYear / monthlyInterval;
> return subsription.Cost * yearlyPaymentCount;
> 
> edit: I just stepped through and saw it's an int, so it doesn't get actual average. I can just use decimal and it will return an actual average?
> 
> "calculate average cost of a subscription for one year. Including Yearly subscriptions even if they have an interval > 1"
> 
> Sorry I'm having trouble understanding this bit.

Its not average cost, check the example ive written that should explain why the current calculation doesnt work - due to intervals. A subscription might be paid 2x one year and the next year its only paid once. We only account for one of thoose scenarios right now thats why the best approach is simply to get the average yearly cost. So if a sub is paid every 7 months right now we only count cost for 1 payment for 12 months, in average we would count 1 payment + 5months (remaining of the year). So the best approach in order to avoid duplicated code is to use the existing method for getting monthly average and just *12 the result

**Comment by bigggmoustache** [comment]
Sorry for the misunderstanding. Commit and push have been made.

**Comment by chrisK00** [comment]
> Sorry for the misunderstanding. Commit and push have been made.

Nothing to be sorry about :P
Ill review it after work, 6pm ish
